package replicate

// ModelList is a list of models that can be used with Replicate.
//
// https://replicate.com/pricing
var ModelList = []string{
	// -------------------------------------
	// image model
	// -------------------------------------
	"black-forest-labs/flux-1.1-pro",
	"black-forest-labs/flux-1.1-pro-ultra",
	"black-forest-labs/flux-canny-dev",
	"black-forest-labs/flux-canny-pro",
	"black-forest-labs/flux-depth-dev",
	"black-forest-labs/flux-depth-pro",
	"black-forest-labs/flux-dev",
	"black-forest-labs/flux-dev-lora",
	"black-forest-labs/flux-fill-dev",
	"black-forest-labs/flux-fill-pro",
	"black-forest-labs/flux-pro",
	"black-forest-labs/flux-redux-dev",
	"black-forest-labs/flux-redux-schnell",
	"black-forest-labs/flux-schnell",
	"black-forest-labs/flux-schnell-lora",
	"ideogram-ai/ideogram-v2",
	"ideogram-ai/ideogram-v2-turbo",
	"recraft-ai/recraft-v3",
	"recraft-ai/recraft-v3-svg",
	"stability-ai/stable-diffusion-3",
	"stability-ai/stable-diffusion-3.5-large",
	"stability-ai/stable-diffusion-3.5-large-turbo",
	"stability-ai/stable-diffusion-3.5-medium",
	// 添加 ReplicateModelMapping 的键（简化模型/通用模型名）
	"flux-1.1-pro",
	"flux-1.1-pro-ultra",
	"flux-canny-dev",
	"flux-canny-pro",
	"flux-depth-dev",
	"flux-depth-pro",
	"flux-dev",
	"flux-dev-lora",
	"flux-fill-dev",
	"flux-fill-pro",
	"flux-pro",
	"flux-redux-dev",
	"flux-redux-schnell",
	"flux-schnell",
	"flux-schnell-lora",
	"imagen-3",
	"imagen-3-fast",
	"upscaler",
	"ideogram-v2",
	"ideogram-v2a",
	"ideogram-v2a-turbo",
	"ideogram-v2-turbo",
	"photon",
	"photon-flash",
	"image-01",
	"recraft-20b",
	"recraft-20b-svg",
	"recraft-creative-upscale",
	"recraft-crisp-upscale",
	"recraft-v3",
	"recraft-v3-svg",
	"stable-diffusion-3",
	"stable-diffusion-3.5-large",
	"stable-diffusion-3.5-large-turbo",
	"stable-diffusion-3.5-medium",
	// -------------------------------------
	// language model
	// -------------------------------------
	"anthropic/claude-3.5-haiku",
	"anthropic/claude-3.5-sonnet",
	"anthropic/claude-3.7-sonnet",
	"deepseek-ai/deepseek-r1",
	"ibm-granite/granite-20b-code-instruct-8k",
	"ibm-granite/granite-3.2-8b-instruct",
	"ibm-granite/granite-8b-code-instruct-128k",
	// -------------------------------------
	// video model
	// -------------------------------------
	// "minimax/video-01",  // TODO: implement the adaptor
}

// 模型映射关系
var ReplicateModelMapping = map[string]string{
	"flux-1.1-pro":                     "black-forest-labs/flux-1.1-pro",
	"flux-1.1-pro-ultra":               "black-forest-labs/flux-1.1-pro-ultra",
	"flux-canny-dev":                   "black-forest-labs/flux-canny-dev",
	"flux-canny-pro":                   "black-forest-labs/flux-canny-pro",
	"flux-depth-dev":                   "black-forest-labs/flux-depth-dev",
	"flux-depth-pro":                   "black-forest-labs/flux-depth-pro",
	"flux-dev":                         "black-forest-labs/flux-dev",
	"flux-dev-lora":                    "black-forest-labs/flux-dev-lora",
	"flux-fill-dev":                    "black-forest-labs/flux-fill-dev",
	"flux-fill-pro":                    "black-forest-labs/flux-fill-pro",
	"flux-pro":                         "black-forest-labs/flux-pro",
	"flux-redux-dev":                   "black-forest-labs/flux-redux-dev",
	"flux-redux-schnell":               "black-forest-labs/flux-redux-schnell",
	"flux-schnell":                     "black-forest-labs/flux-schnell",
	"flux-schnell-lora":                "black-forest-labs/flux-schnell-lora",
	"imagen-3":                         "google/imagen-3",
	"imagen-3-fast":                    "google/imagen-3-fast",
	"upscaler":                         "google/upscaler",
	"ideogram-v2":                      "ideogram-ai/ideogram-v2",
	"ideogram-v2a":                     "ideogram-ai/ideogram-v2a",
	"ideogram-v2a-turbo":               "ideogram-ai/ideogram-v2a-turbo",
	"ideogram-v2-turbo":                "ideogram-ai/ideogram-v2-turbo",
	"photon":                           "luma/photon",
	"photon-flash":                     "luma/photon-flash",
	"image-01":                         "minimax/image-01",
	"recraft-20b":                      "recraft-ai/recraft-20b",
	"recraft-20b-svg":                  "recraft-ai/recraft-20b-svg",
	"recraft-creative-upscale":         "recraft-ai/recraft-creative-upscale",
	"recraft-crisp-upscale":            "recraft-ai/recraft-crisp-upscale",
	"recraft-v3":                       "recraft-ai/recraft-v3",
	"recraft-v3-svg":                   "recraft-ai/recraft-v3-svg",
	"stable-diffusion-3":               "stability-ai/stable-diffusion-3",
	"stable-diffusion-3.5-large":       "stability-ai/stable-diffusion-3.5-large",
	"stable-diffusion-3.5-large-turbo": "stability-ai/stable-diffusion-3.5-large-turbo",
	"stable-diffusion-3.5-medium":      "stability-ai/stable-diffusion-3.5-medium",
}
