package cloudflare

var ModelList = []string{
	// "@cf/meta/llama-3.1-8b-instruct",
	// "@cf/meta/llama-2-7b-chat-fp16",
	// "@cf/meta/llama-2-7b-chat-int8",
	// "@cf/mistral/mistral-7b-instruct-v0.1",
	// "@hf/thebloke/deepseek-coder-6.7b-base-awq",
	// "@hf/thebloke/deepseek-coder-6.7b-instruct-awq",
	// "@cf/deepseek-ai/deepseek-math-7b-base",
	// "@cf/deepseek-ai/deepseek-math-7b-instruct",
	// "@cf/thebloke/discolm-german-7b-v1-awq",
	// "@cf/tiiuae/falcon-7b-instruct",
	// "@cf/google/gemma-2b-it-lora",
	// "@hf/google/gemma-7b-it",
	// "@cf/google/gemma-7b-it-lora",
	// "@hf/nousresearch/hermes-2-pro-mistral-7b",
	// "@hf/thebloke/llama-2-13b-chat-awq",
	// "@cf/meta-llama/llama-2-7b-chat-hf-lora",
	// "@cf/meta/llama-3-8b-instruct",
	// "@hf/thebloke/llamaguard-7b-awq",
	// "@hf/thebloke/mistral-7b-instruct-v0.1-awq",
	// "@hf/mistralai/mistral-7b-instruct-v0.2",
	// "@cf/mistral/mistral-7b-instruct-v0.2-lora",
	// "@hf/thebloke/neural-chat-7b-v3-1-awq",
	// "@cf/openchat/openchat-3.5-0106",
	// "@hf/thebloke/openhermes-2.5-mistral-7b-awq",
	// "@cf/microsoft/phi-2",
	// "@cf/qwen/qwen1.5-0.5b-chat",
	// "@cf/qwen/qwen1.5-1.8b-chat",
	// "@cf/qwen/qwen1.5-14b-chat-awq",
	// "@cf/qwen/qwen1.5-7b-chat-awq",
	// "@cf/defog/sqlcoder-7b-2",
	// "@hf/nexusflow/starling-lm-7b-beta",
	// "@cf/tinyllama/tinyllama-1.1b-chat-v1.0",
	// "@hf/thebloke/zephyr-7b-beta-awq",
	// 文本生成
	// deepseek
	"@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
	"@cf/deepseek-ai/deepseek-math-7b-instruct",
	// google
	"@cf/google/gemma-3-12b-it",
	"@cf/google/gemma-7b-it-lora",
	// meta
	"@cf/meta/llama-4-scout-17b-16e-instruct",
	"@cf/meta/llama-3.3-70b-instruct-fp8-fast",
	// qwen
	"@cf/qwen/qwq-32b",
	"@cf/qwen/qwen2.5-coder-32b-instruct",
	// 图片生成模型
	"flux-1-schnell",
	"@cf/black-forest-labs/flux-1-schnell",
	"stable-diffusion-xl-base-1.0",
	"@cf/stabilityai/stable-diffusion-xl-base-1.0",
	"stable-diffusion-xl-lightning",
	"@cf/bytedance/stable-diffusion-xl-lightning",
	"stable-diffusion-v1-5-img2img",
	"@cf/runwayml/stable-diffusion-v1-5-img2img",
	"dreamshaper-8-lcm",
	"@cf/lykon/dreamshaper-8-lcm",
	"stable-diffusion-v1-5-inpainting",
	"@cf/runwayml/stable-diffusion-v1-5-inpainting",
}

var CloudflareModelMapping = map[string]string{
	"flux-1-schnell":                   "@cf/black-forest-labs/flux-1-schnell",
	"stable-diffusion-xl-lightning":    "@cf/bytedance/stable-diffusion-xl-lightning",
	"stable-diffusion-v1-5-img2img":    "@cf/runwayml/stable-diffusion-v1-5-img2img",
	"dreamshaper-8-lcm":                "@cf/lykon/dreamshaper-8-lcm",
	"stable-diffusion-v1-5-inpainting": "@cf/runwayml/stable-diffusion-v1-5-inpainting",
	"stable-diffusion-xl-base-1.0":     "@cf/stabilityai/stable-diffusion-xl-base-1.0",
}
